### PR TITLE
Parse schema version as ASN1 object identifier

### LINKED ISSUE #81: Ability to parse version string of schema (ASN.1)
In metanorma/annotated-express#38 there is a need to find out parts of an EXPRESS schema version string.

The SCHEMA version string can be in ASN.1 format:

From 10303-11:
```
SCHEMA geometry_schema ’version_1’;
```

=> `schema.version.string` => `'version_1'`

From 10303-11:
```
SCHEMA support_resource_schema ’{ISO standard 10303 part(41) object(1) version(8)}’;
```

=> 
```
schema.version.string
=> '{ISO standard 10303 part(41) object(1) version(8)}'

schema.version.asn1[3].name
=> '10303'

schema.version.asn1[4].name
=> 'part'

schema.version.asn1[4].value
=> '41'
```

In STEPmod:
```
SCHEMA action_schema '{iso standard 10303 part(41) version(8) object(1) action_schema(1)}';
```

Then we can do:

```adoc
// `schemas` is all schemas
// `schema` is one schema
{% assign reference_froms = schema.interfaces | where: "kind", :REFERENCE %}
{% for from in reference_froms %}
{% assign ref_schema = schemas | where: "id", from.schema.id %}
{{ from.schema.id }}:: ISO {{ ref_schema.version.asn1[3].name}}-{{ ref_schema.version.asn1[4].value }}
{% endfor %}
```

### PR DESCRIPTION
**Pull request by zakjan**
Fixes #81

### CODE REVIEW

**Comment by zakjan** [comment]
Behavior implemented: schema version string literal is parsed as ASN1 object identifier with a simple custom code https://github.com/lutaml/expressir/blob/26d4730a57c777af69fe54d3cf330ff63fda0765/lib/expressir/express_exp/visitor.rb#L2528-L2560

If parsing succeeds, hash contains new Asn1ObjectIdentifier and Asn1ObjectIdentifierItem instances:

```
  version:
    _class: Expressir::Model::Asn1ObjectIdentifier
    items:
    - _class: Expressir::Model::Asn1ObjectIdentifierItem
      name: ISO
    - _class: Expressir::Model::Asn1ObjectIdentifierItem
      name: standard
    - _class: Expressir::Model::Asn1ObjectIdentifierItem
      value: 10303
    - _class: Expressir::Model::Asn1ObjectIdentifierItem
      name: part
      value: 41
    - _class: Expressir::Model::Asn1ObjectIdentifierItem
      name: object
      value: 1
    - _class: Expressir::Model::Asn1ObjectIdentifierItem
      name: version
      value: 8
```

If parsing fails, hash contains the usual string literal:

```
  version:
    _class: Expressir::Model::Literals::String
    value: version
```

I haven't added registered values (iso = 1, standard = 0), because they would cause a different formatted output.

@ronaldtse Is it good for your use case?

**Comment by zakjan** [comment]
I have merged the two variants into a single SchemaVersion for easier handling, so that the original version string is always retained. I assume that schema version is the only occurrence of ASN1 object identifiers in EXPRESS.

```
  version:
    _class: Expressir::Model::SchemaVersion
    value: version
```
and
```
  version:
    _class: Expressir::Model::SchemaVersion
    value: "{ISO standard 10303 part(41) object(1) version(8)}"
    items:
    - _class: Expressir::Model::SchemaVersionItem
      name: ISO
    - _class: Expressir::Model::SchemaVersionItem
      name: standard
    - _class: Expressir::Model::SchemaVersionItem
      value: '10303'
    - _class: Expressir::Model::SchemaVersionItem
      name: part
      value: '41'
    - _class: Expressir::Model::SchemaVersionItem
      name: object
      value: '1'
    - _class: Expressir::Model::SchemaVersionItem
      name: version
      value: '8'
```

**Comment by zakjan** [comment]
@ronaldtse I assume it's good, merging and releasing as 0.2.27. Let me know if it works for you, or you need further changes.

**Comment by ronaldtse** [comment]
Looks great, thanks @zakjan !

**Pull request merged**
