### PR TITLE
Stability fixes, additional tests and verification

### PR DESCRIPTION
**Pull request by maxirmx**

### CODE REVIEW

**Comment by maxirmx** [comment]
This PR includes the following enhancements:
-- finalized fixes for segfaults in C++ native extension  in sync with PR placed towards antlr4-native-rb
-- added native extension sanity checks to CI scripts
-- added rubocop run to CI scripts, some of ruby files are fixed to meet desired rubocop criteria
-- added verification of pakaged gems in CI scripts (this is critical since development and release procedures use different toolchains)

**Comment by maxirmx** [comment]
UPD  
This PR includes the following enhancements:
- finalized fixes for segfaults in C++ native extension ( using antlr4-native-rb 2.0.0.1 )
- added native extension sanity checks to CI scripts
- added rubocop run to CI scripts, some of ruby files are fixed to meet desired rubocop criteria
- added verification of pakaged gems in CI scripts (this is critical since development and release procedures use different toolchains)
- cleaned obsolete files
- fixed build for x64-mingw-ucrt binary gem

**Comment by ronaldtse** [comment]
@maxirmx please feel free to merge when ready, thanks!

**Review by CAMOBAP — APPROVED** [review]
Great job, a lot of improvements

@maxirmx to be on the same page did antlr4 upgrade lead to any breaking changes? I see a lot of exp files was updated

I'm asking because recently we faced with such situation in https://github.com/lutaml/lutaml/pull/35

**Comment by maxirmx** [comment]
> Great job, a lot of improvements
> 
> @maxirmx to be on the same page did antlr4 upgrade lead to any breaking changes? I see a lot of exp files was updated
> 
> I'm asking because recently we faced with such situation in [lutaml/lutaml#35](https://github.com/lutaml/lutaml/pull/35)

ANTLR README says:
" Generated 4.10 lexers and parsers are incompatible with code generated by previous versions of ANTLR. You must regenerate all of your code from grammars to use the new runtime."  
So I regenerated all C++ files.  However,  there was no need to touch Ruby expressir code or fix anything in rspec tests. I assume that all C++ changed are hidden by Rice and Ruby wrappers.

**Comment by ronaldtse** [comment]
Hope it works!

**Pull request merged**
