### PR TITLE
Rice 4.0

### LINKED ISSUE #95: (URGENT) Upgrade rice gem to 4.0
Required for packed-mn. (also from https://github.com/tamatebako/tebako/issues/55)

### PR DESCRIPTION
**Pull request by alexeymorozov**
Closes #95

Work on a fork is here: https://github.com/camertron/antlr4-native-rb/compare/master...lutaml:rice-4

### CODE REVIEW

**Comment by alexeymorozov** [comment]
It requires the `stl` support, which was included in rice v4.0.2, and which dropped support of Ruby 2.5.

As far as I know we support Ruby 2.5 currently, so we may create a PR to rice which restores 2.5.

**Comment by ronaldtse** [comment]
Thank you @alexeymorozov ! Would be great if you can make a PR to `rice` to add support for Ruby 2.5. Once that is done we can finally be complete with the new stack!

**Comment by alexeymorozov** [comment]
Created a PR https://github.com/jasonroelofs/rice/pull/165

**Review by ronaldtse — APPROVED** [review]
Thank you @alexeymorozov ! This is wonderful.

**Comment by ronaldtse** [comment]
@alexeymorozov can you help make a PR upstream for antlr4-native-rb? Please also update their gemspec so that it requires rice version ~4.0. Thanks!

**Comment by ronaldtse** [comment]
@alexeymorozov also need release. Thanks!

**Pull request merged**
