### PR TITLE
Pure ruby

### PR DESCRIPTION
**Pull request by kwkwan**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP can you please help check the "verify install" jobs? While Expressir is now in pure Ruby, we technically don't need these platform-specific tests anymore, but to be able to test the install is still useful. Thanks!

**Comment by ronaldtse** [comment]
@CAMOBAP once this is done, please help merge and release a new major release. Thanks!

**Comment by CAMOBAP** [comment]
"verify install" jobs seems doesn't make much sese to me now.

They run rspec on gem after installation in the local rubygems directory of ruby,

For now, it fails because tests are excluded from the gem

@ronaldtse @kwkwan these jobs have to be dropped

**Comment by ronaldtse** [comment]
My original intent for these jobs are just to ensure we can install the built gems. Since it's not necessary, let's drop them. Thanks.

**Comment by ronaldtse** [comment]
Thank you!

**Pull request merged**
