### PR TITLE
Add formatted to schema drop

### PR DESCRIPTION
**Pull request by kwkwan**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@kwkwan does this obsolete #157 ?

**Comment by kwkwan** [comment]
> @kwkwan does this obsolete #157 ?

No, it still relies on `to_s` method.

**Comment by ronaldtse** [comment]
So we want a `to_s` method to generate the schemas in these ways:

Remarks:
* with remarks
* with no remarks

Formatted:
* pretty-printed
* original

Do you think these should all go into `to_s`?

**Comment by kwkwan** [comment]
For the use cases in `suma` and `iso-10303`, I think it is fine.  However, I have no idea on the other cases.

**Pull request merged**
