### PR TITLE
Feature/migrate to vanila rubocop config #92

### PR DESCRIPTION
**Pull request by CAMOBAP**
- really hard to fix all the issues at once, i tried my best to fix the most

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP thanks! Can you help run these commands?

```
rubocop -A
rubocop --auto-gen-config -A
```

**Review by maxirmx — APPROVED** [review]
I believe it is good enough as a first step towards vanilla rubocop config

**Comment by CAMOBAP** [comment]
> @CAMOBAP thanks! Can you help run these commands?
> 
> ```
> rubocop -A
> rubocop --auto-gen-config -A
> ```

Good catch, put back rubocop and added rubocop_todo.yml

**Comment by ronaldtse** [comment]
Thank you @camobap and @maxirmx !

**Pull request merged**
