### PR TITLE
Use YARD for documentation

### LINKED ISSUE #72: Express model documentation
Currently, there is no explicit Express model documentation. All available classes, members, and usage can be seen directly in [model classes](https://github.com/lutaml/expressir/tree/master/lib/expressir/model) and [sample input file](https://github.com/lutaml/expressir/blob/master/original/examples/syntax/syntax.exp) + [parser test](https://github.com/lutaml/expressir/blob/master/spec/expressir/express_exp/parser/syntax_spec.rb).

How shall we document it? Separate AsciiDoc file? RDoc?

### PR DESCRIPTION
**Pull request by zakjan**
Fixes #72

### CODE REVIEW

**Comment by zakjan** [comment]
@ronaldtse Please take a look. I focused especially on model attribute types.

[doc.zip](https://github.com/lutaml/expressir/files/6370671/doc.zip)

**Comment by zakjan** [comment]
Regarding deployment, it seems that YARD docs can be automatically published at https://rubydoc.info/

**Comment by ronaldtse** [comment]
Looks great, thanks!

**Comment by zakjan** [comment]
@ronaldtse Releasing as 1.1.0, because changes in the model structure are quite heavy.

There is one change needed in https://github.com/metanorma/annotated-express/blob/master/data/documents/resources/fundamentals_of_product_description_and_support/sections/04-schemas.adoc:
Expressir::Model::Types::Select -> Expressir::Model::DataTypes::Select

**Comment by zakjan** [comment]
Docs is deployed at https://rubydoc.info/github/lutaml/expressir

**Comment by ronaldtse** [comment]
Excellent, thanks!

**Comment by ronaldtse** [comment]
Fixed metanorma/annotated-express@1fac13a as described.

**Pull request merged**
