### PR TITLE
Add cache support

### LINKED ISSUE #49: Support exporting and importing a parse tree cache
From lutaml/lutaml-express#4:

We want to allow a defined set (via YAML or XML) of EXPRESS schemas available for Metanorma to navigate.

This requires Expressir to have the following functionality:

- fully parse all the schemas and keep them around
- for speed reasons, Expressir should support exporting/importing a parsed cache that contains the schema set

### PR DESCRIPTION
**Pull request by zakjan**
Fixes #49

### CODE REVIEW

**Comment by ronaldtse** [comment]
@zakjan are we ready to merge this? Thanks.

**Comment by zakjan** [comment]
May I ask how is the cache going to be used? in which environments, how long can it live, how do you expect to refresh it etc. I'd prefer to remove Expressir version from it, keep the functionality that exports/imports gzipped yaml only. is it ok?

**Comment by ronaldtse** [comment]
Right now the cache is only used in compiling metanorma documents. 

It can live for a very long time as long as the referenced schemas are not changed.

It would probably be useful to keep a "cache schema version" in it to ensure that the writer and reader of the cache is compatible.

**Comment by zakjan** [comment]
> for a very long time as long as the referenced schemas are not changed

Does it mean it would be stored together in the repo with source files? I expected it to be used locally only.

> to ensure that the writer and reader of the cache is compatible

Yes, but it's going to fail only in the client. Or should it fallback to the parser? Every Expressir release would need to trigger regenerating the cache, so that it's always valid with the most recent version.

**Comment by zakjan** [comment]
In my opinion, such cache persisted to the repo brings unnecessary complication to the architecture. Can I spend some time investigating parser performance instead? It seems that recently introduced post-parsing steps (attaching remarks, hyperlink formatting) have negative impact on the performance, because they search for objects in the parse tree, and can be improved.

**Comment by ronaldtse** [comment]
See this automated build. On GHA, the document finishes compilation after 3 hours. On my computer, 20 minutes. From the percentage of use, I surmise that GHA spends at least 1 hour in the parser for 24 schemas.

https://github.com/metanorma/annotated-express/runs/2055518291?check_suite_focus=true

**Comment by zakjan** [comment]
There is a slight improvement in parse & format performance thanks to small changes implemented in #70.

Total processing time for [24 documents in annotated-express](https://github.com/metanorma/annotated-express/blob/master/data/documents/resources/fundamentals_of_product_description_and_support/sections/04-schemas.adoc) is ~10.7s in sc4-formatting branch, opposed to ~13.6s in master. That's 21% improvement.

What duration would you consider as an acceptable baseline in order to not need the persisted cache?

Benchmark code:

```
exp_files = [
  Expressir.root_path.join('../iso-10303-stepmod/data/resources/action_schema/action_schema_annotated.exp'),
  Expressir.root_path.join('../iso-10303-stepmod/data/resources/application_context_schema/application_context_schema_annotated.exp'),
  Expressir.root_path.join('../iso-10303-stepmod/data/resources/approval_schema/approval_schema_annotated.exp'),
  Expressir.root_path.join('../iso-10303-stepmod/data/resources/basic_attribute_schema/basic_attribute_schema_annotated.exp'),
  Expressir.root_path.join('../iso-10303-stepmod/data/resources/certification_schema/certification_schema_annotated.exp'),
  Expressir.root_path.join('../iso-10303-stepmod/data/resources/contract_schema/contract_schema_annotated.exp'),
  Expressir.root_path.join('../iso-10303-stepmod/data/resources/date_time_schema/date_time_schema_annotated.exp'),
  Expressir.root_path.join('../iso-10303-stepmod/data/resources/document_schema/document_schema.exp'),
  Expressir.root_path.join('../iso-10303-stepmod/data/resources/effectivity_schema/effectivity_schema_annotated.exp'),
  Expressir.root_path.join('../iso-10303-stepmod/data/resources/experience_schema/experience_schema_annotated.exp'),
  Expressir.root_path.join('../iso-10303-stepmod/data/resources/external_reference_schema/external_reference_schema_annotated.exp'),
  Expressir.root_path.join('../iso-10303-stepmod/data/resources/group_schema/group_schema_annotated.exp'),
  Expressir.root_path.join('../iso-10303-stepmod/data/resources/language_schema/language_schema_annotated.exp'),
  Expressir.root_path.join('../iso-10303-stepmod/data/resources/location_schema/location_schema_annotated.exp'),
  Expressir.root_path.join('../iso-10303-stepmod/data/resources/management_resources_schema/management_resources_schema_annotated.exp'),
  Expressir.root_path.join('../iso-10303-stepmod/data/resources/measure_schema/measure_schema_annotated.exp'),
  Expressir.root_path.join('../iso-10303-stepmod/data/resources/person_organization_schema/person_organization_schema_annotated.exp'),
  Expressir.root_path.join('../iso-10303-stepmod/data/resources/process_property_schema/process_property_schema_annotated.exp'),
  Expressir.root_path.join('../iso-10303-stepmod/data/resources/product_definition_schema/product_definition_schema_annotated.exp'),
  Expressir.root_path.join('../iso-10303-stepmod/data/resources/product_property_definition_schema/product_property_definition_schema_annotated.exp'),
  Expressir.root_path.join('../iso-10303-stepmod/data/resources/product_property_representation_schema/product_property_representation_schema_annotated.exp'),
  Expressir.root_path.join('../iso-10303-stepmod/data/resources/qualifications_schema/qualifications_schema_annotated.exp'),
  Expressir.root_path.join('../iso-10303-stepmod/data/resources/security_classification_schema/security_classification_schema_annotated.exp'),
  Expressir.root_path.join('../iso-10303-stepmod/data/resources/support_resource_schema/support_resource_schema_annotated.exp'),
]

start = Time.now
repo = Expressir::ExpressExp::Parser.from_files(exp_files)
repo.to_hash(formatter: Class.new(Expressir::ExpressExp::Formatter) do
  include Expressir::ExpressExp::SchemaHeadFormatter
  include Expressir::ExpressExp::HyperlinkFormatter
end)
puts Time.now - start
```

**Comment by ronaldtse** [comment]
@zakjan we’re traversing the tree — can you help profile the time LutaML is spending in Expressir?

**Comment by zakjan** [comment]
Where does Lutaml traverse the tree? I think it only calls `repository.to_hash` with the custom formatter, returning a hash ([example](https://github.com/lutaml/expressir/blob/sc4-formatting/original/examples/syntax/syntax.yaml)), which is passed to the template.

**Comment by zakjan** [comment]
I was able to track down only these three relevant usages of Expressir in Lutaml.

- Parser.from_files - https://github.com/lutaml/lutaml/blob/master/lib/lutaml/parser.rb#L37
- repository.to_hash - https://github.com/lutaml/lutaml/blob/master/lib/lutaml/express/lutaml_path/document_wrapper.rb#L11-L12
- Formatter - https://github.com/lutaml/lutaml/blob/master/lib/lutaml/express/lutaml_path/formatter.rb

**Comment by zakjan** [comment]
Total processing time in Expressir of all 1246 annotated files: 

Parsing time: 6m18s
Formatting & serializing time: 8s
Total time: 6m26s

**Comment by zakjan** [comment]
Total processing time in Expressir of all 1246 annotated files: 

master:

Parsing time: 7m53s
Formatting & serializing time: unknown, didn't finished in reasonable time
Total time: unknown

sc4-formatting branch:

Parsing time: 6m18s (20% improvement)
Formatting & serializing time: 8s
Total time: 6m26s

**Comment by zakjan** [comment]
Hmm, caching in GHA cache probably needs a different strategy than caching in the repo. The gem / script running in GHA would need to take care about refreshing the cache when it is invalid.

**Comment by zakjan** [comment]
24 files:
```
Parser.from_files time:  10.94s
Cache.to_file time:      0.54s
Cache.from_file time:    0.38s
Repository.to_hash time: 0.28s
```

1246 files:
```
Parser.from_files time:  328.9s
Cache.to_file time:      20.4s
Cache.from_file time:    14s
Repository.to_hash time: 7.4s
```

**Comment by zakjan** [comment]
I have finished implementation in this PR. It throws if Expressir version doesn't match. Current usage is:

```rb
begin
  repository = Expressir::ExpressExp::Cache.from_file(cache_file)
rescue Expressir::ExpressExp::CacheLoadError
  repository = Expressir::ExpressExp::Parser.from_files(files)
  Expressir::ExpressExp::Cache.to_file(cache_file, repository)
end
```

The usage can be improved further.

**Comment by ronaldtse** [comment]
@zakjan looks good! @w00lf can you help incorporate this in LutaML? Thanks.

**Comment by w00lf** [comment]
> @zakjan looks good! @w00lf can you help incorporate this in LutaML? Thanks.

Ok, will do

**Comment by zakjan** [comment]
Is it good to merge and release, or do we need further improvements?

**Comment by ronaldtse** [comment]
@zakjan let's release since you've confirmed it works. @w00lf can have a separate ticket to use it in lutaml.

**Comment by zakjan** [comment]
Release 0.2.20 running

**Comment by w00lf** [comment]
> @zakjan let's release since you've confirmed it works. @w00lf can have a separate ticket to use it in lutaml.

Will be implemented in https://github.com/lutaml/lutaml/issues/13

**Pull request merged**
