### PR TITLE
Cleanup

### LINKED ISSUE #15: Migrate Expressir::Express classes to use Expressir::Model classes
The older set of EXPRESS classes are under the namespace of `Expressir::Express`, such as: `Expressir::Express::AggregateDimension`.

The new set of EXPRESS classes are under `Expressir::Model`, e.g. `Expressir::Model::Statements`.

This task is to replace the older set with the new classes.

### LINKED ISSUE #52: Remove XML parser
Expressir does not need to read from XML anymore.

The OWL functionality should be re-based on the new EXPRESS parse nodes.

### LINKED ISSUE #77: Better naming
Where class -> WhereRule
Unique class -> UniqueRule

Type / Entity / Rule class
- where -> where_rules
- unique -> unique_rules

Type class
- type -> underlying_type

Types::Select / Types::Enumeration class
- extension_type -> based_on
- extension_items -> items

### PR DESCRIPTION
**Pull request by zakjan**
Fixes #52 
Fixes #77
Closes #15 (no longer applicable)

---

Breaking changes:
- previous XML parser (Expressir::Express module in directory expressir/express) is removed, see #52
- module Expressir::ExpressExp is renamed to Expressir::Express, directory expressir/express_exp is renamed to expressir/express
- class Expressir::ExpressExp::CacheLoadError is removed, already existing Expressir::Error is thrown instead
- naming of some model classes and attributes is improved, see #77

Other changes:
- Nokogiri dependency is removed, see https://github.com/lutaml/expressir/issues/40

To be released as ~0.3.0~ 1.0.0

### CODE REVIEW

**Comment by zakjan** [comment]
@ronaldtse Could you review this, please?

**Review by ronaldtse — APPROVED** [review]
LGTM!

**Comment by ronaldtse** [comment]
@zakjan since this PR will break existing functionality, can you update the major version number?

Ping @w00lf will need to update lutaml-express with this new version.

**Comment by zakjan** [comment]
Sure, we can make it 1.0.0 🎉

**Comment by ronaldtse** [comment]
That's awesome! Please feel free to merge and bump version...

**Comment by zakjan** [comment]
Released. annotated-express templates are also going to have to be updated

**Pull request merged**
